# Generated by Django 5.0.6 on 2024-07-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='contact_information',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_name',
            field=models.TextField(),
        ),
    ]
