# Generated by Django 5.0.6 on 2024-07-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_parser', '0002_alter_vacancy_contact_information_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='contact_information',
            new_name='information',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='counters',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='metro',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='professional_roles',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='archived',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employement',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='schedule',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
