# Generated by Django 5.0.6 on 2024-07-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_parser', '0004_rename_employement_vacancy_employment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='salary',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(default='RUR', max_length=5),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='max_salary',
            field=models.IntegerField(default=2147483647),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='min_salary',
            field=models.IntegerField(default=0),
        ),
    ]
