# Generated by Django 5.0.6 on 2024-07-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_parser', '0005_remove_vacancy_salary_vacancy_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='max_salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='min_salary',
            field=models.IntegerField(),
        ),
    ]
