# Generated by Django 5.0.6 on 2024-07-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_parser', '0006_alter_vacancy_currency_alter_vacancy_max_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(default='RUR', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='max_salary',
            field=models.IntegerField(default=2147483647, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='min_salary',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
